In [1]:
MAX = 100
def luDecomposition(mat, n):

    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]

    # Decomposing matrix into Upper
    # and Lower triangular matrix
    for i in range(n):

        # Upper Triangular
        for k in range(i, n):

            # Summation of L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])

            # Evaluating U(i, k)
            upper[i][k] = mat[i][k] - sum

        # Lower Triangular
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal as 1
            else:

                # Summation of L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])

                # Evaluating L(k, i)
                lower[k][i] = int((mat[k][i] - sum) /
                                  upper[i][i])

    # setw is for displaying nicely
    print("Lower Triangular\t\tUpper Triangular")

    # Displaying the result :
    for i in range(n):

        # Lower
        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")

        # Upper
        for j in range(n):
            print(upper[i][j], end="\t")
        print("")


# Driver code
mat = [[2, -1, -2],
       [-4, 6, 3],
       [-4, -2, 8]]

luDecomposition(mat, 3)

# This code is contributed by mits

Lower Triangular		Upper Triangular
1	0	0		2	-1	-2	
-2	1	0		0	4	-1	
-2	-1	1		0	0	3	


In [ ]:

import numpy as np
from scipy.linalg import lu

# Example dataset as a matrix
A = np.array([[2, 1, 1],
              [4, -6, 0],
              [-2, 7, 2]])

# Perform LU decomposition
P, L, U = lu(A)

# Output the results
print("Original Matrix (A):")
print(A)

print("\nPermutation Matrix (P):")
print(P)

print("\nLower Triangular Matrix (L):")
print(L)

print("\nUpper Triangular Matrix (U):")
print(U)

# Verify the decomposition
# A = P @ L @ U
reconstructed_A = P @ L @ U
print("\nReconstructed Matrix (should be equal to A):")
print(reconstructed_A)

Original Matrix (A):
[[ 2  1  1]
 [ 4 -6  0]
 [-2  7  2]]

Permutation Matrix (P):
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

Lower Triangular Matrix (L):
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5  1.   1. ]]

Upper Triangular Matrix (U):
[[ 4. -6.  0.]
 [ 0.  4.  1.]
 [ 0.  0.  1.]]

Reconstructed Matrix (should be equal to A):
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]
